#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastros1.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BancoEmpresa")]
	public partial class Cadastros1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblFuncionario(tblFuncionario instance);
    partial void UpdatetblFuncionario(tblFuncionario instance);
    partial void DeletetblFuncionario(tblFuncionario instance);
    partial void InserttblSetor(tblSetor instance);
    partial void UpdatetblSetor(tblSetor instance);
    partial void DeletetblSetor(tblSetor instance);
    #endregion
		
		public Cadastros1DataContext() : 
				base(global::Cadastros1.DATA.Properties.Settings.Default.BancoEmpresaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Cadastros1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cadastros1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cadastros1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cadastros1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblFuncionario> tblFuncionarios
		{
			get
			{
				return this.GetTable<tblFuncionario>();
			}
		}
		
		public System.Data.Linq.Table<tblSetor> tblSetors
		{
			get
			{
				return this.GetTable<tblSetor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFuncionario")]
	public partial class tblFuncionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nldFuncionario;
		
		private string _sNome;
		
		private System.DateTime _sNascimento;
		
		private string _sCPF;
		
		private string _sCargo;
		
		private int _nldSetor;
		
		private string _sSalario;
		
		private EntityRef<tblSetor> _tblSetor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnldFuncionarioChanging(int value);
    partial void OnnldFuncionarioChanged();
    partial void OnsNomeChanging(string value);
    partial void OnsNomeChanged();
    partial void OnsNascimentoChanging(System.DateTime value);
    partial void OnsNascimentoChanged();
    partial void OnsCPFChanging(string value);
    partial void OnsCPFChanged();
    partial void OnsCargoChanging(string value);
    partial void OnsCargoChanged();
    partial void OnnldSetorChanging(int value);
    partial void OnnldSetorChanged();
    partial void OnsSalarioChanging(string value);
    partial void OnsSalarioChanged();
    #endregion
		
		public tblFuncionario()
		{
			this._tblSetor = default(EntityRef<tblSetor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nldFuncionario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nldFuncionario
		{
			get
			{
				return this._nldFuncionario;
			}
			set
			{
				if ((this._nldFuncionario != value))
				{
					this.OnnldFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._nldFuncionario = value;
					this.SendPropertyChanged("nldFuncionario");
					this.OnnldFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNome", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string sNome
		{
			get
			{
				return this._sNome;
			}
			set
			{
				if ((this._sNome != value))
				{
					this.OnsNomeChanging(value);
					this.SendPropertyChanging();
					this._sNome = value;
					this.SendPropertyChanged("sNome");
					this.OnsNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNascimento", DbType="Date NOT NULL")]
		public System.DateTime sNascimento
		{
			get
			{
				return this._sNascimento;
			}
			set
			{
				if ((this._sNascimento != value))
				{
					this.OnsNascimentoChanging(value);
					this.SendPropertyChanging();
					this._sNascimento = value;
					this.SendPropertyChanged("sNascimento");
					this.OnsNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sCPF", DbType="Char(14) NOT NULL", CanBeNull=false)]
		public string sCPF
		{
			get
			{
				return this._sCPF;
			}
			set
			{
				if ((this._sCPF != value))
				{
					this.OnsCPFChanging(value);
					this.SendPropertyChanging();
					this._sCPF = value;
					this.SendPropertyChanged("sCPF");
					this.OnsCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sCargo", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string sCargo
		{
			get
			{
				return this._sCargo;
			}
			set
			{
				if ((this._sCargo != value))
				{
					this.OnsCargoChanging(value);
					this.SendPropertyChanging();
					this._sCargo = value;
					this.SendPropertyChanged("sCargo");
					this.OnsCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nldSetor", DbType="Int NOT NULL")]
		public int nldSetor
		{
			get
			{
				return this._nldSetor;
			}
			set
			{
				if ((this._nldSetor != value))
				{
					if (this._tblSetor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnldSetorChanging(value);
					this.SendPropertyChanging();
					this._nldSetor = value;
					this.SendPropertyChanged("nldSetor");
					this.OnnldSetorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSalario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sSalario
		{
			get
			{
				return this._sSalario;
			}
			set
			{
				if ((this._sSalario != value))
				{
					this.OnsSalarioChanging(value);
					this.SendPropertyChanging();
					this._sSalario = value;
					this.SendPropertyChanged("sSalario");
					this.OnsSalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSetor_tblFuncionario", Storage="_tblSetor", ThisKey="nldSetor", OtherKey="nldSetor", IsForeignKey=true)]
		public tblSetor tblSetor
		{
			get
			{
				return this._tblSetor.Entity;
			}
			set
			{
				tblSetor previousValue = this._tblSetor.Entity;
				if (((previousValue != value) 
							|| (this._tblSetor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSetor.Entity = null;
						previousValue.tblFuncionarios.Remove(this);
					}
					this._tblSetor.Entity = value;
					if ((value != null))
					{
						value.tblFuncionarios.Add(this);
						this._nldSetor = value.nldSetor;
					}
					else
					{
						this._nldSetor = default(int);
					}
					this.SendPropertyChanged("tblSetor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSetor")]
	public partial class tblSetor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nldSetor;
		
		private string _sSetor;
		
		private EntitySet<tblFuncionario> _tblFuncionarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnldSetorChanging(int value);
    partial void OnnldSetorChanged();
    partial void OnsSetorChanging(string value);
    partial void OnsSetorChanged();
    #endregion
		
		public tblSetor()
		{
			this._tblFuncionarios = new EntitySet<tblFuncionario>(new Action<tblFuncionario>(this.attach_tblFuncionarios), new Action<tblFuncionario>(this.detach_tblFuncionarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nldSetor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nldSetor
		{
			get
			{
				return this._nldSetor;
			}
			set
			{
				if ((this._nldSetor != value))
				{
					this.OnnldSetorChanging(value);
					this.SendPropertyChanging();
					this._nldSetor = value;
					this.SendPropertyChanged("nldSetor");
					this.OnnldSetorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSetor", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string sSetor
		{
			get
			{
				return this._sSetor;
			}
			set
			{
				if ((this._sSetor != value))
				{
					this.OnsSetorChanging(value);
					this.SendPropertyChanging();
					this._sSetor = value;
					this.SendPropertyChanged("sSetor");
					this.OnsSetorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSetor_tblFuncionario", Storage="_tblFuncionarios", ThisKey="nldSetor", OtherKey="nldSetor")]
		public EntitySet<tblFuncionario> tblFuncionarios
		{
			get
			{
				return this._tblFuncionarios;
			}
			set
			{
				this._tblFuncionarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblFuncionarios(tblFuncionario entity)
		{
			this.SendPropertyChanging();
			entity.tblSetor = this;
		}
		
		private void detach_tblFuncionarios(tblFuncionario entity)
		{
			this.SendPropertyChanging();
			entity.tblSetor = null;
		}
	}
}
#pragma warning restore 1591
